
INSERT INTO USERS (EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PROFILE_INFORMATION, ROLES, USERNAME)
VALUES ('example@email.com', 'John', 'Doe', 'encrypted_password', 'This is profile information', 'USER',
        'john.doe');

INSERT INTO ACCOUNTS (BALANCE, USER_ENTITY_ID, ACCOUNT_TYPE)
VALUES (123, 'john.doe', 'Debit');

INSERT INTO CATEGORIES (NAME, DESCRIPTION)
VALUES ('abc', 'abc');

INSERT INTO BUDGETS (USER_ENTITY_ID, AMOUNT, CATEGORY_ID, START_DATE, END_DATE)
VALUES ('john.doe', 123, 1, '2024-01-01', '2024-02-02');

INSERT INTO GOALS (CURRENT_AMOUNT, TARGET_AMOUNT, TARGET_DATE, USER_ENTITY_ID, NAME)
VALUES (123, 123, '2024-01-01', 'john.doe', 'SAVING');

INSERT INTO TRANSACTIONS (AMOUNT, ACCOUNT_ID, CATEGORY_ID, DATE, TYPE)
VALUES (123, 1, 1, '2024-01-01', 'transaction')